## Synthetic population pipeline for Île-de-France
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: D:\TraDD ENPC 2020-21\Stage\MODUSv3.1.3\M3_Chaine\Modus_Python\output
# Kiko - somehow this is the command that creates the cache folder. 

# This section defines which parts of the pipeline should be run
run:
   - generation


# Here the configuraiton of the pipeline starts
config:
# Some general configuration
   cNbZone:  1289      # nombre de zones interne Idf
   cNbDpt:  8          # nombre de départements : DPRT
   cNbCour:  3         # nombre de couronnes : COUR
   cNbClacc:  6        # nombre de classes d'accessibilité TC : CLACC
# 2. Désagrégation
   cNbMotif:  22       # nombre de motifs à la génération
   cNbMotifD:  14      # nombre de motifs à la distribution
   cNbMotifC:  11      # nombre de motifs au choix modal
   cNbCat:  2          # nombre de catégories dans la désagrégation
   cNbTot:  cNbMotif*cNbCat        # nombre total de types de déplacements
   cNbTot_D:  cNbMotifD*cNbCat     # nombre total de types de déplacements
   cNbTot_C:  cNbMotifC*cNbCat     # nombre total de types de déplacements
   Niv:  DPRT      # niveau géographique (avec le nom utilisé dans la table calibr.zone) pour la désagrégation
   NivO:  ORDPRT   # niveau géographique de l'EGT pour la désagrégation à l'origine
   NivD:  DESTDPRT     # niveau géographique de l'EGT pour la désagrégation à la destination
   cNbNiv:  cNbDpt     # nombre d'éléments dans le niveau géographique de l'EGT pour la désagrégation
 # CARACTÉRISTIQUES DU CALIBRAGE
 # 0. Variables diverses
   cNbClasse:  8   # nombre de classes de portée
   Classe1:  0.75  # seuil max de la classe 1 en km
   Classe2:  1.25  # seuil max de la classe 2 en km
   Classe3:  2.0   # seuil max de la classe 3 en km
   Classe4:  3.5   # seuil max de la classe 4 en km
   Classe5:  6.0   # seuil max de la classe 5 en km
   Classe6:  9.0   # seuil max de la classe 6 en km
   Classe7:  15.0  # seuil max de la classe 7 en km
   VARGEN:  ['PTOT', 'PACT', 'PACTHQ', 'PACTAQ', 'RETR', 'SCOLSUP','SCOLSEC', 'SCOLPRIM','PSCOL', 'CHOM', 'PNACTA', 'PNACTACHO',
           'PINACT', 'ETOT', 'EMPHQ', 'EMPAQ', 'EMPCOM', 'EMPLOI', 'EMPACH', 'SUP_LE', 'SEC_LE', 'PRIM_LE', 'SCOL_LE']
 # !. Macrovariables de MODUS 3
 # 0. Caractéristiques du zonage
 # hors zones internes, cNbZones défini dans le fichier de constantes du calibrage
   cNbZgare:  12   # nombre de zones gares
   cNbZext:  34    # nombre de zones du cordon
   cNbZspec:  4    # nombre de zones spécifiques externes
   cNbZtot:  cNbZspec+cNbZext      # nombre total de zones affectation VP
 # Kiko cNbZtot:  %eval(&cNbZone+&cNbZspec+&cNbZext) Problème: version originelle, mais c'est quoi cNbZone?
 
 # 1. Horizons considérés
   actuel:  2012   # année de la situation de calage du modèle
   scen:  2022     # année de la situation de scénario > actuel
   caleVP:  2012
   caleTC:  2012
 
 # 2. Périodes horaires simulées
   PPM:  1     # exécution ou non de la simulation en PPM
   PCJ:  0     # exécution ou non de la simulation en PCJ
   PPS:  1     # exécution ou non de la simulation en PPS
 
 # 3. Méthode demande PL
 # a. choix de la méthode
   idPL:  2    #: 0, 1, 2 ou 3 selon la méthode choisie parmi les quatre ci  dessous
 
 # b. Méthodes
 #      méthode 0 : pas de prise en compte des PL dans l'affectation
 #      méthode 1 : projection des matrices de flux PL calées par période horaire selon la croissance du PIB
   CroisPIB:  1.5      # % de croissance annuelle du PIB : 1.5%
 
 #      méthode 2 : utilisation d'une matrice flux PL journalière interne IdF et de cordons PL actuelle et projetée pour
 # déterminer les évolutions par OD à appliquer aux matrices PL calées par période horaire définies dans la méthode 1
 
 #     méthode 3 : utilisation de matrices de flux PL projetées par période horaire
 
 # 4. Paramètre du report de calage
 
   idVP:  1    # identifiant d'exécution (=1) ou pas (=0) du report de calage VP
   idTC:  1    # identifiant d'exécution (=1) ou pas (=0) du report de calage TC
   k0:  1.77   # seuil de croissance extreme avant prise en compte du taux de croissance annuel de la méthode de report de
 # calage n°2
   cSeuilh:  2 # borne de l'amplification multiplicative de la méthode de report de calage n°1
   cSeuilb:  0.25  # borne de la réduction multiplicative de la méthode de report de calage n°1
 # calzonage:  Zone  C'est quoi zone?
 
 # 5. Bouclage
   idBcl:  1       # identifiant d'exécution du bouclage sur la distribution (=1), le choix modal (=2), le choix modal
 # restreint aux modes motorisés (=3), le choix modal restreint aux modes véhiculés (=4) ou pas du tout (=0)
   cConv_M:  50    # critère de convergence du bouclage en HPM (ex : 100 pour le bouclage sur la dist, 30 pour le choix modal)
   cConv_C:  50    # critère de convergence du bouclage en HC (ex : 100 pour le bouclage sur la dist, 30 pour le choix modal)
   cConv_S:  50    # critère de convergence du bouclage en HPS (ex : 100 pour le bouclage sur la dist, 30 pour le choix modal)
   cNbBcl:  10     # nombre maximum d'itérations lors du bouclage    doit être >1
   cParTpsBcl:  0.5  # paramètre du bouclage pour la pondération des temps des itérations n  1 et n
   cParMatBcl:  0.5    # paramètre du bouclage pour la pondération des matrices des itérations n  1 et n
 
 # 6. Vecteurs Spécifiques
 # a. identifiant d'éxécution de l'implémentation des vecteurs spécifiques
   IdVsVp:  1      # identifiant d'implémentation (=1) ou pas (=0) des vecteurs spécifiques VP
   IdVsTc:  1      # identifiant d'implémentation (=1) ou pas (=0) des vecteurs spécifiques TC
   IdcorADP:  1    # identifiant d'implémentation (=1) ou pas (=0) des corrections de volume UVP sur base des études
 # d'impact d'ADP sur T4
   IdmethodeVSTC:  2   # méthode de calcul des VS TC : basée sur le choix modal de Modus (=1) ou basée sur la
 # génération/distribution de Modus (=2)
 
 # b. Numérotation des zones spécifiques
   cZEmpCDG:  1290     # Zone spécifique associée aux emplois de la plateforme de Roissy  CDG
   cZVoyCDG:  1291     # Zone spécifique associée aux voyageurs de la plateforme de Roissy  CDG
   cZEmpOrly:  1292    # Zone spécifique associée aux emplois de la plateforme d'Orly
   cZVoyOrly:  1293    # Zone spécifique associée aux voyageurs de la plateforme d'Orly
   ZoneCDG:  (245, 995, 1249)      # Liste des zones CDG
   ZoneOrly:  (679, 1078)      # Liste des zones Orly
 
 # 7. Vecteurs Gares
   idVGTC:  1  # Implémentation ou non des vecteurs voyageurs TC émis et attiré par les gares
   idVGVP:  0  # Implémentation ou non des vecteurs voyageurs VP émis et attiré par les gares
 
 # 8. Lecture fichiers VISUM TempsM.csv, TempsC.csv et TempsS.csv
   deb:  32    # ligne de début= 32 si Temps seul sans péage;: 33 si Temps et Peage
 
 
 # 9. Télétravail
   idTTV:  0   # 1:  activation du module télétravail en scénario, 0 sinon
   jourTTV:  0.3    # part moyenne du temps de travail réalisée en télétravail (nb jour télétravaillé / nb jour travaillé)
   partTTV:  0.75   # part des emplois télétravaillables occupées par des télétravailleurs
   tauxTTVHQ:  0.85     # part des emplois HQ télétravaillables : 0.85 selon DADDT 2020
   tauxTTVAQact:  0.228    # part des actifs AQ occupant un emploi télétravaillable : 0.228 selon DADDT 2020
   tauxTTVAQemp:  0.228     # part des emplois AQ télétravaillables : 0.228 selon DADDT 2020
   varJTTVpro:  0.07       # ratio de mobilité professionnelle un jour télétravaillé : 0.07 selon ADEME 2020
   varJLTHpro:  1.00       # ratio de mobilité professionnelle un jour en lieu de travail habituel : 1.00 selon ADEME 2020
   varJTTVacc:  1.00      # ratio de mobilité accompagnement un jour télétravaillé : 0.55 selon ADEME 2020, 1.00 si inactif
   varJLTHacc:  1.00      # ratio de mobilité accompagnement un jour en lieu de travail habituel : 1.13 selon ADEME 2020,
 # 1.00 si inactif
   varJTTVaut:  1.00   # ratio de mobilité autres un jour télétravaillé : 0.43 selon ADEME 2020, 1.00 si inactif
   varJLTHaut:  1.00  # ratio de mobilité autres un jour en lieu de travail habituel :
 # 1.16 selon ADEME 2020, 1.00 si inactif
   tauxTTVAQ:  Path_sep(os.path.join(dir_dataScen, 'tauxTTVAQ.txt'), '\t')

 #  Kiko do I import tauxTTVAQ here or in the file where it's used.
 
 # 10. Vélo
 
   idvelo:  0
   intcy:  0.7
   capvelib:  1
 
 # 11. Croissance du coût d'usage de la voiture
 
   idcoutvp:  1    # 1:  activation de l'augmentation du coût vp, 0 sinon
   croiscarb:  2   # pourcentage de croissance annuelle du coût des carburants en € constant:  2%/an entre 2015 et 2030
   croisentr:  1   # pourcentage de croissance annuelle du coût d'entretien des VP en € constant:  1%/an entre 2015 et 2030
   croispeag:  0   # pourcentage de croissance annuelle du coût des péages des VP en € constant
   n: actuel
   per: PPM


  # Population_Emplois
  Pop_Emp_actuel: D:\TraDD ENPC 2020-21\Stage\MODUSv3.1.3\Donnees\Input\1_Actuel\bdzone2012.sas7bdat
  Pop_Emp_scen: D:\TraDD ENPC 2020-21\Stage\MODUSv3.1.3\Donnees\Input\2_Scenario\bdzone2022.sas7bdat


  
